### ISSUE TITLE
How to transfer a 3D voxel CNN model to your LieConv?

### ISSUE THREAD

**Issue by xuzhang5788** [mfinzi/LieConv#3]
Thank you for your great work. 
I have a 3D voxel CNN model. Because of a lack of data, I have to do data argumentation many times. And also the dataset is very sparse, so it is not efficient for memory. I want to transfer my model into a se(3) model. However, I don't know how to prepare my dataset. 
In addition, how is your model difference from e3nn and se(3)cnn?

Many thanks.

**Comment by mfinzi** [comment]
LieConv networks process inputs like pointclouds, so you will want to perform this conversion to transform to a collection of 3D coordinates and values with shapes (bs,n,d) and (bs,n,c) where bs is the batchsize, n is the total number of points (aka sampling locations) and d=3 for your 3d data and c may be 1 for occupancy or higher if you have additional features that are input. For sparse voxel data, this will mean assigning coordinates to each of the occupied voxels and ignoring the rest.

The differences between LieConv-SE(3) models and [Tensor Field Networks](https://arxiv.org/abs/1802.08219) or the recent [SE(3)-Transformers](https://arxiv.org/pdf/2006.10503.pdf) stem from the use of the regular representation of SO(3) rather than the irreducible representations. This leads to fewer constraints on the model, such as being able to use pointwise nonlinearities instead of more specialized ones, and more easily apply to different groups. For reasons that may not be entirely well understood, the regular representation tends to outperform the irreducible or other representations, as shown thoroughly in [E(2)-Steerable CNNs](https://arxiv.org/abs/1911.08251). One can view our work as a method of implementing the regular representation for continuous groups.
