### ISSUE TITLE
Error occur

### ISSUE THREAD

**Issue by clara9gian** [mfinzi/LieConv#8]
Hello,
I am very interested in your code and I have it a try.
but this error happend when I am trying to run your code.

Traceback (most recent call last):
  File "examples/train_springs.py", line 9, in <module>
    from lie_conv.datasets import SpringDynamics
  File "/home/em308/LieConv/lie_conv/datasets.py", line 58, in <module>
    class ModelNet40(Dataset,metaclass=Named):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Since I am very new in programming, would you mind to tell me what can I do to solve this?
thank you so much for your help.

**Comment by mfinzi** [comment]
Hi Clara,
I think this must because the pytorch Dataset class in pytorch has had it's metaclass changed since the repo was released. In general in python an object can only have one metaclass, and if a parent class has a different metaclass that causes a conflict.
The quick fix here would be to remove metaclass=Named for these dataset objects, which I will do tomorrow, as this was merely a convenience for representing results when running on multiple distinct datasets.
- Marc

**Comment by mfinzi** [comment]
I have now removed all the metaclass usage in the repo. This should have no functional change on the models, and was only a convenience for hyperparameter tuning and organizing the results of experiments.

**Comment by clara9gian** [comment]
Good afternoon, Professor.
Thank you for helping me regarding the issues.
May I know how to save the model from your training and how to write the
test program?
I am very sorry for asking a dumb question since this is my first time try
to code.
